language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - postgresql
addons:
    postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_install:
  - chmod +x mvnw
before_script:
  - psql -c 'DROP DATABASE IF EXISTS postgres;' -U postgres
  - psql -c 'CREATE DATABASE postgres;' -U postgres
after_success:
  - bash <(curl -s https://codecov.io/bash)
